name: Semgrep

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/semgrep.yml

permissions:
  contents: read
  security-events: write

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    
    if: (github.actor != 'dependabot[bot]')
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # Run Semgrep scan and generate SARIF in one step
      - name: Semgrep Scan
        run: |
          # Run scan and generate SARIF directly
          semgrep ci --sarif > semgrep-results.sarif || true
          # Ensure the SARIF file exists and has valid JSON
          if [ -s semgrep-results.sarif ]; then
            echo "SARIF file generated successfully"
          else
            echo "Creating empty SARIF result"
            echo '{"version":"2.1.0","runs":[{"tool":{"driver":{"name":"semgrep","version":"1.0.0"}},"results":[]}]}' > semgrep-results.sarif
          fi
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
          
      - name: Upload SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-results.sarif
